name: test

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  pull_request:
    branches:
      - main # Trigger on Pull Requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14' # Version from your package.json

      - name: Install dependencies
        run: npm ci # Use ci for more reliable installs in CI

      - name: Run tests
        run: npm test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          TEST_TOKEN: ${{secrets.TEST_TOKEN}}
          NEXT_PUBLIC_HASURA_GRAPHQL_URL: ${{secrets.NEXT_PUBLIC_HASURA_GRAPHQL_URL}}
          HASURA_ADMIN_SECRET: ${{secrets.HASURA_ADMIN_SECRET}}
          HASURA_JWT_SECRET: ${{secrets.HASURA_JWT_SECRET}}
          HASURA_EVENT_SECRET: ${{secrets.HASURA_EVENT_SECRET}}
          NEXT_PUBLIC_MAIN_URL: ${{secrets.NEXT_PUBLIC_MAIN_URL}}
          NEXT_PUBLIC_BASE_URL: ${{secrets.NEXT_PUBLIC_BASE_URL}}
          NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
          NEXT_PUBLIC_API_URL: ${{secrets.NEXT_PUBLIC_API_URL}}
          NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          YANDEX_CLIENT_ID: ${{secrets.YANDEX_CLIENT_ID}}
          YANDEX_CLIENT_SECRET: ${{secrets.YANDEX_CLIENT_SECRET}}
          RESEND_API_KEY: ${{secrets.RESEND_API_KEY}}
          GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{secrets.NEXT_PUBLIC_FIREBASE_API_KEY}}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID}}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{secrets.NEXT_PUBLIC_FIREBASE_APP_ID}}
          NEXT_PUBLIC_FIREBASE_VAPID_KEY: ${{secrets.NEXT_PUBLIC_FIREBASE_VAPID_KEY}}
          VERCEL_URL: ${{secrets.VERCEL_URL}}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
          TELEGRAM_ADMIN_CHAT_ID: ${{secrets.TELEGRAM_ADMIN_CHAT_ID}}
          NEXT_PUBLIC_PROJECT_USER_ID: ${{secrets.NEXT_PUBLIC_PROJECT_USER_ID}}
          NEXT_PUBLIC_APP_NAME: ${{secrets.NEXT_PUBLIC_APP_NAME}}
          FACEBOOK_CLIENT_ID: ${{secrets.FACEBOOK_CLIENT_ID}}
          FACEBOOK_CLIENT_SECRET: ${{secrets.FACEBOOK_CLIENT_SECRET}}
          VK_CLIENT_ID: ${{secrets.VK_CLIENT_ID}}
          VK_CLIENT_SECRET: ${{secrets.VK_CLIENT_SECRET}}
          TELEGRAM_BOT_NAME: ${{secrets.TELEGRAM_BOT_NAME}}
          TELEGRAM_CHANNEL_ID: ${{secrets.TELEGRAM_CHANNEL_ID}}
          TBANK_PROD_TERMINAL_KEY: ${{secrets.TBANK_PROD_TERMINAL_KEY}}
          TBANK_PROD_SECRET_KEY: ${{secrets.TBANK_PROD_SECRET_KEY}}
          TBANK_TEST_TERMINAL_KEY: ${{secrets.TBANK_TEST_TERMINAL_KEY}}
          TBANK_TEST_SECRET_KEY: ${{secrets.TBANK_TEST_SECRET_KEY}}
          TBANK_USE_TEST_MODE: ${{secrets.TBANK_USE_TEST_MODE}}
          TBANK_DEFAULT_RETURN_URL: ${{secrets.TBANK_DEFAULT_RETURN_URL}}
          TBANK_DEFAULT_WEBHOOK_URL: ${{secrets.TBANK_DEFAULT_WEBHOOK_URL}}
          TBANK_DEFAULT_CARD_WEBHOOK_URL: ${{secrets.TBANK_DEFAULT_CARD_WEBHOOK_URL}}
          PROJECT_USER_EMAIL: ${{secrets.PROJECT_USER_EMAIL}}
          PROJECT_USER_PASSWORD: ${{secrets.PROJECT_USER_PASSWORD}}
          OPENROUTER_API_KEY: ${{secrets.OPENROUTER_API_KEY}}